name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: 'http://localhost:3333'
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          npm ci
          npm run test
      - uses: codecov/codecov-action@v1
        with:
          directory: ./tests/coverage/
