name: Pipeline
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_URL: 'http://localhost:3333'
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '16.13'
      - uses: actions/checkout@v4
      - name: Run test
        run: |
          npm ci
          npm run test
      - uses: codecov/codecov-action@v5
        with:
          directory: ./tests/coverage/
